#Dockerfile.streamlit
FROM python:3.10-slim

WORKDIR /app

# Requirements & Code kopieren
COPY requirements.streamlit.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py ./app.py
COPY auth.py ./auth.py


# Optional: Erstelle leeres Verzeichnis, falls nicht vorhanden
RUN mkdir -p ./data/predictions

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]