version: '3.8'

services:
  streamlit:
    build:
      context: ../
      dockerfile: streamlit_app/Dockerfile.streamlit
    container_name: streamlit_app
    ports:
      - "8501:8501"
    restart: unless-stopped