{
 "title": "Movie Recommender",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": " Precision@10 vs Drift – Dual-Axis Panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "model_precision_at_10{model=\"Deep Hybrid-KNN_best\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "drift_score_sliding_window{model=\"hybrid_deep_model\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Precision@10",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "model_precision_at_10", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Training Loss per Epoch",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "training_loss", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Heatmap Histogramm  prediction_confidence",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(prediction_confidence_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Conversion Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "targets": [
    { "expr": "conversion_rate{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Health Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "targets": [
    { "expr": "health_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Share of Drifted Columns",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "data_drift_share{model=\"Deep Hybrid-KNN_best\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "drift_score_sliding_window",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "drift_score_sliding_window{model=\"Deep Hybrid-KNN_best\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "drift_score_sliding_window{model=\"hybrid_deep_model\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Drift Alert Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 27 },
   "targets": [
    { "expr": "drift_alert", "legendFormat": "__auto" },
    {
     "expr": "drift_alert{model=\"Deep Hybrid-KNN_Last_Trained\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "drift_alert{model=\"Deep Hybrid-KNN_best_Model\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Drift Alert Status (0/1)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 27 },
   "targets": [
    { "expr": "model_drift_alert", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "\trecommendation_requests_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "recommendation_requests_totalrecommendation_latency_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Volume per Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "rate(recommendation_requests_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency Models",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "recommendation_latency_seconds_sum",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "API Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "\trecommendation_api_usage_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}