global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'bento_service'
    static_configs:
      - targets: ['bentoml:3000']

  - job_name: 'ml_api'
    static_configs:
      - targets: ['api_service:8000']