global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'bento_service'
    static_configs:
      - targets: ['bentoml:4000']

  - job_name: "api_service"
    metrics_path: /metrics
    static_configs:
      - targets: ["api_service:8000"]

  - job_name: 'drift_metrics_api'
    metrics_path: /metrics/drift
    static_configs:
      - targets: ['api_service:8000']

  - job_name: 'airflow_drift'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics
    scrape_interval: 15s


  - job_name: 'precision_metrics'
    metrics_path: /metrics/training
    static_configs:
    - targets: ['api_service:8000']
    
  - job_name: 'textfile-metrics'
    static_configs:
      - targets: ['node_exporter:9100']
