version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - airflow_net

  airflow-init:
    build:
      context: ../
      dockerfile: airflow/Dockerfile.airflow
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__WEBSERVER__SECRET_KEY: 'my_super_secret_key_42'
      PYTHONPATH: /opt/airflow:/opt/airflow/src
      AIRFLOW_UID: 50000
    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - ../airflow/plugins:/opt/airflow/plugins
      - ../airflow/logs:/opt/airflow/logs
      - ../src:/opt/airflow/src
      - ../data:/opt/airflow/data
    command: >
      bash -c "airflow db migrate &&
               airflow users create --username airflow --password airflow --firstname Admin --lastname User --role Admin --email admin@example.com"
    networks:
      - airflow_net

  airflow-webserver:
    build:
      context: ../
      dockerfile: airflow/Dockerfile.airflow
    restart: always
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: airflow
      _AIRFLOW_WWW_USER_PASSWORD: airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: 'my_super_secret_key_42'
      AIRFLOW__LOGGING__REMOTE_LOGGING: 'False'
      PYTHONPATH: /opt/airflow:/opt/airflow/src
      AIRFLOW_UID: 50000
    ports:
      - "8080:8080"
    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - ../airflow/plugins:/opt/airflow/plugins
      - ../airflow/logs:/opt/airflow/logs
      - ../src:/opt/airflow/src
      - ../data:/opt/airflow/data
    command: >
      bash -c "airflow webserver"
    networks:
      - airflow_net

  airflow-scheduler:
    build:
      context: ../
      dockerfile: airflow/Dockerfile.airflow
    restart: always
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: 'my_super_secret_key_42'
      PYTHONPATH: /opt/airflow:/opt/airflow/src
      AIRFLOW_UID: 50000
    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - ../airflow/plugins:/opt/airflow/plugins
      - ../airflow/logs:/opt/airflow/logs
      - ../src:/opt/airflow/src
      - ../data:/opt/airflow/data
    command: >
      bash -c "airflow scheduler"
    networks:
      - airflow_net

volumes:
  postgres_db:

networks:
  airflow_net: