FROM apache/airflow:2.8.1-python3.10

# Installiere zusätzliche Python-Abhängigkeiten
COPY airflow/requirements.airflow.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt

# Erstelle interne Verzeichnisse mit Rechten (nicht notwendig für Host-Volumes!)
RUN mkdir -p /opt/airflow/data/processed